app_mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_blog.views import custom_permission_denied
from app_mailing.apps import AppMailingConfig
from app_mailing.views import MainPage, MailingSrvListView, MailingSrvCreateView, MailingSrvUpdateView, \
    MailingSrvDetailView, MailingSrvDeleteView, MailListView, MailCreateView, MailUpdateView, MailDetailView, \
    MailDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView, LogListView, \
    LogDetailView, LogDeleteView, send_mailing_btn, MailingSrvCustomUpdateView

app_name = AppMailingConfig.name

urlpatterns = [
    # path('', MainPage.as_view(), name='home'),
    path('', cache_page(60)(MainPage.as_view()), name='home'),
    path('mailings_list/', MailingSrvListView.as_view(), name='mailings_list'),
    path('mailings_create/', MailingSrvCreateView.as_view(), name='mailings_create'),
    path('mailings_update/<int:pk>/', MailingSrvUpdateView.as_view(), name='mailings_update'),
    path('mailings_custom_update/<int:pk>/', MailingSrvCustomUpdateView.as_view(), name='mailings_custom_update'),
    path('mailings_detail/<int:pk>/', MailingSrvDetailView.as_view(), name='mailings_detail'),
    path('mailings_delete/<int:pk>/', MailingSrvDeleteView.as_view(), name='mailings_delete'),
    path('<int:pk>/', send_mailing_btn, name='send_mailing_btn'),
    path('mail_list/', MailListView.as_view(), name='mail_list'),
    path('mail_create/', MailCreateView.as_view(), name='mail_create'),
    path('mail_update/<int:pk>/', MailUpdateView.as_view(), name='mail_update'),
    path('mail_detail/<int:pk>/', MailDetailView.as_view(), name='mail_detail'),
    path('mail_delete/<int:pk>/', MailDeleteView.as_view(), name='mail_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('log_list/', LogListView.as_view(), name='log_list'),
    path('log_detail/<int:pk>/', LogDetailView.as_view(), name='log_detail'),
    path('log_delete/<int:pk>/', LogDeleteView.as_view(), name='log_delete'),
    path('access_denied/', custom_permission_denied, name='access_denied'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_mailing.urls', namespace='app_mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('app_blog.urls', namespace='app_blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, get_verification, RegisterInfo, UserListView, \
    UserUpdateView, UserDetailView, UserDeleteView, PasswordResetView, UserPasswordChangeView, PasswordResetDoneView, \
    PasswordResetCompleteView, MyPasswordResetConfirmView, UserCustomUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification_check/', RegisterInfo.as_view(), name='verification_check'),
    path('email_verify/<str:verification_code>/', get_verification, name='verification'),
    path('verification_approve/', TemplateView.as_view(
        template_name='users/verification_approve.html'), name='verification_approve'),
    path('verification_reject/', TemplateView.as_view(
        template_name='users/verification_reject.html'), name='verification_reject'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('user_custom_update/<int:pk>/', UserCustomUpdateView.as_view(), name='user_custom_update'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user_delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

app_mailing/models.py
from django.db import models
from django.utils import timezone

from users.models import User

# Create your models here.

NULLABLE = {
    'null': True,
    'blank': True,
}


class Client(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь-владелец', **NULLABLE)
    email = models.EmailField(max_length=100, unique=True, verbose_name='почтовый адрес')
    initials = models.CharField(max_length=50, verbose_name='инициалы')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f'{self.initials} ({self.email})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mail(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь-владелец', **NULLABLE)
    subject = models.CharField(max_length=150, verbose_name='тема письма')
    content = models.TextField(verbose_name='тело письма')

    mailings = models.ForeignKey('MailingSrv', on_delete=models.CASCADE, verbose_name='рассылки',
                                 related_name='mails', **NULLABLE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'


class MailingSrv(models.Model):
    AT_ONCE = 'единоразово'
    BY_DAY = 'раз в день'
    BY_WEEK = 'раз в неделю'
    BY_MONTH = 'раз в месяц'

    FREQUENCY = [
        (AT_ONCE, 'единоразово'),
        (BY_DAY, 'раз в день'),
        (BY_WEEK, 'раз в неделю'),
        (BY_MONTH, 'раз в месяц')
    ]

    CREATED = 'создана'
    PROCESSING = 'запущена'
    FINISHED = 'завершена'

    STATUS = [
        (CREATED, 'создана'),
        (PROCESSING, 'запущена'),
        (FINISHED, 'завершена')
    ]

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь-владелец', **NULLABLE)
    recipients = models.ManyToManyField(Client, verbose_name='получатели рассылки')
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name='письмо', **NULLABLE)
    start = models.DateTimeField(default=timezone.now, verbose_name='время начала рассылки')
    next = models.DateTimeField(default=timezone.now, verbose_name='время следующей рассылки')
    finish = models.DateTimeField(verbose_name='время завершения рассылки')
    status = models.CharField(max_length=100, choices=STATUS, default=STATUS[0], verbose_name='статус рассылки')
    frequency = models.CharField(max_length=50, choices=FREQUENCY, verbose_name='периодичность рассылки')
    is_activated = models.BooleanField(default=True, verbose_name='метка активности')

    def __str__(self):
        return f'Рассылка_{self.pk}: {self.frequency} - {self.status}'

    class Meta:
        verbose_name = 'параметр рассылки'
        verbose_name_plural = 'параметры рассылок'
        ordering = ('pk',)

        permissions = [
            ('set_is_activated', 'переключатель метки активности')
        ]


class Log(models.Model):
    attempt_time = models.DateTimeField(auto_now=True, verbose_name='время последней попытки')
    status = models.CharField(max_length=50, verbose_name='статус попытки', default='попытка не инициирована')
    server_response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(MailingSrv, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE)

    def __str__(self):
        return f'Отчет {self.pk}:  Статус - {self.status}( Когда - {self.attempt_time})'

    class Meta:
        verbose_name = 'отчет'
        verbose_name_plural = 'отчеты'
        ordering = ('mailing',)

app_mailing/forms.py
from django import forms
from django.forms import DateTimeInput

from app_mailing.models import MailingSrv, Mail, Client


class StyleFormMiXin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_activated' and field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


class MailingSrvForm(StyleFormMiXin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['recipients'].queryset = Client.objects.filter(owner=user)
        self.fields['mail'].queryset = Mail.objects.filter(owner=user)

    start = forms.DateTimeField(
        label='Время начала рассылки',
        required=False,
        widget=DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M')
    )

    finish = forms.DateTimeField(
        label='Время окончания рассылки',
        required=False,
        widget=DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M')
    )

    class Meta:
        model = MailingSrv
        exclude = ('next', 'owner', 'is_activated',)


class MailingSrvCustomForm(StyleFormMiXin, forms.ModelForm):

    class Meta:
        model = MailingSrv
        fields = ('is_activated',)


class MailForm(StyleFormMiXin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['mailings'].queryset = MailingSrv.objects.filter(owner=user)

    class Meta:
        model = Mail
        exclude = ('owner',)


class ClientForm(StyleFormMiXin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)

app_mailing/templates/app_mailing/access_denied.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<div style="display: flex; justify-content: center;">

    <h4 class="card-title">
        Доступ ограничен. Обратитесь к администратору.
    </h4>

</div>
{% endblock %}

app_mailing/templates/app_mailing/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body>

{% include 'app_mailing/includes/inc_header.html' %}

<div class="card text-center">
  <div class="card-body">
    <h1 class="text-lg text-primary">{{ title }}</h1>
  </div>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Возможности нашего сервиса:</p>
    <h5 class="display-12">{{ phrases }}</h5>
</div>

{% block content %}
{% endblock %}


{% include 'app_mailing/includes/inc_footer.html' %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/holder.min.js"></script>
<script>
    Holder.addTheme('thumb', {
      bg: '#55595c',
      fg: '#eceeef',
      text: 'Thumbnail'
    });
</script>
</body>
</html>

app_mailing/templates/app_mailing/client_detail.html
{% extends 'app_mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиент номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Инициалы клиента: {{ object.initials | upper }}</li>
                    <li>Почтовый адрес клиента: {{ object.email }}</li>
                    <li>Комментарий: {{ object.comment }}</li>
                </ul>
                <div class="btn-group">
                    <a href="{% url 'app_mailing:client_delete' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Удалить</a>
                    <a href="{% url 'app_mailing:client_update' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Редактировать</a>
                    <a href="{% url 'app_mailing:client_list' %}" type="button"
                       class="btn btn-sm btn-outline-primary">К списку</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_mailing/templates/app_mailing/client_form.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                   <button type="submit" class="btn btn-success">
                                       {% if object %}
                                            Сохранить изменения
                                       {% else %}
                                            Создать
                                       {% endif %}
                                   </button>
                                <a href="{% url 'app_mailing:client_list' %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_mailing/templates/app_mailing/client_list.html
{% extends 'app_mailing/base.html' %}

{% block content %}

<div class="container">
    <a href="{% url 'app_mailing:client_create' %}" class="btn btn-primary">Добавить клиента</a>
</div>

<div class="container">
    {% for object in object_list %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиент номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <details>
                    <summary>Подробности</summary>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Инициалы клиента: {{ object.initials | upper }}</li>
                        <li>Почтовый адрес клиента: {{ object.email }}</li>
                        <li>Комментарий: {{ object.comment }}</li>
                    </ul>
                </details>

                <div class="btn-group">
                    <a href="{% url 'app_mailing:client_detail' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Посмотреть</a>
                    <a href="{% url 'app_mailing:client_update' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Редактировать</a>
                    <a href="{% url 'app_mailing:client_delete' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app_mailing/templates/app_mailing/log_confirm_delete.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить отчет "{{ object.pk }}" ?</p>
                                   <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'app_mailing:log_detail' object.pk %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_mailing/templates/app_mailing/log_detail.html
{% extends 'app_mailing/base.html' %}

{% block content %}


<div class="container">
    {% for data in mailing_data %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h6 class="my-0 font-weight-normal">{{ data.log.mailing }}</h6>
                <h6 class="my-0 font-weight-normal">Время начала: {{ data.log.mailing.start|date:"Y-m-d H:i" }}</h6>
            </div>
            <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Время последней попытки: {{ data.log.attempt_time }}</li>
                        <li>Статус попытки рассылки: {{ data.log.status }}</li>
                        <li>Ответ почтового сервера: {{ data.log.server_response }}</li>
                    </ul>

                    <hr>

                    <ul class="list-unstyled mt-3 mb-4">
                        {% for recipient_data in data.recipients_data %}
                        <li>Почтовый ящик: {{ recipient_data.email }} (ФИО: {{ recipient_data.initials }})</li>
                        {% endfor %}
                    </ul>

                <div class="btn-group">
                    <a href="{% url 'app_mailing:log_list' %}" type="button"
                       class="btn btn-sm btn-outline-primary">К списку</a>
                    <a href="{% url 'app_mailing:log_delete' data.log.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app_mailing/templates/app_mailing/mail_confirm_delete.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить письмо "{{ object.pk }}" ?</p>
                                   <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'app_mailing:mail_detail' object.pk %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_mailing/templates/app_mailing/mail_form.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                   <button type="submit" class="btn btn-success">
                                       {% if object %}
                                            Сохранить изменения
                                       {% else %}
                                            Создать
                                       {% endif %}
                                   </button>
                                <a href="{% url 'app_mailing:mail_list' %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_mailing/templates/app_mailing/mail_list.html
{% extends 'app_mailing/base.html' %}

{% block content %}

<div class="container">
    <a href="{% url 'app_mailing:mail_create' %}" class="btn btn-primary">Добавить письмо для рассылки</a>
</div>

<div class="container">
    {% for object in object_list %}
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Письмо номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <details>
                    <summary>Подробности</summary>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Тема письма: {{ object.subject }}</li>
                        <li>Содержимое письма: {{ object.content }}</li>
                    </ul>
                </details>

                <div class="btn-group">
                    <a href="{% url 'app_mailing:mail_detail' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Посмотреть</a>
                    <a href="{% url 'app_mailing:mail_update' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Редактировать</a>
                    <a href="{% url 'app_mailing:mail_delete' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-primary">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app_mailing/templates/app_mailing/mailingsrv_confirm_delete.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить рассылку "{{ object.pk }}" ?</p>
                                   <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'app_mailing:mailings_detail' object.pk %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_mailing/templates/app_mailing/mailingsrv_detail.html
{% extends 'app_mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Рассылка номер: {{ object.id }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Периодичность рассылки: {{ object.frequency }}</li>
                    <li>Время начала рассылки: {{ object.start }}</li>
                    <li>Время следующей рассылки: {{ object.next }}</li>
                    <li>Время завершения рассылки: {{ object.finish }}</li>
                    <li>Статус рассылки: {{ object.status }}</li>
                </ul>

                <hr>

                <ul class="list-unstyled mt-3 mb-4">
                    {% for recipient_data in mailing_data.0.recipients_data %}
                    {% if mail_subject %}
                        <li>Тема письма: {{ mail_subject }}</li>
                    {% else %}
                        <li>Письмо не назначено</li>
                    {% endif %}
                    <li>Почтовый ящик: {{ recipient_data.email }} (ФИО: {{ recipient_data.initials }})</li>
                    {% endfor %}
                </ul>


                <div class="btn-group">

                    {% if perms.app_mailing.set_is_activated %}
                        <a href="{% url 'app_mailing:mailings_custom_update' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>

                        <a href="{% url 'app_mailing:mailings_list' %}" type="button"
                           class="btn btn-sm btn-outline-primary">К списку</a>
                    {% else %}

                        <a href="{% url 'app_mailing:mailings_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Удалить</a>

                        <a href="{% url 'app_mailing:mailings_update' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>

                        <a href="{% url 'app_mailing:mailings_list' %}" type="button"
                           class="btn btn-sm btn-outline-primary">К списку</a>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_mailing/templates/app_mailing/mailingsrv_form.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                   <button type="submit" class="btn btn-success">
                                       {% if object %}
                                            Сохранить изменения
                                       {% else %}
                                            Создать
                                       {% endif %}
                                   </button>
                                <a href="{% url 'app_mailing:mailings_list' %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_mailing/templates/app_mailing/mailingsrv_list.html
{% extends 'app_mailing/base.html' %}

{% block content %}

<div class="container">
    {% if user.is_superuser or not user.groups.exists %}
        <a href="{% url 'app_mailing:mailings_create' %}" class="btn btn-primary">Добавить рассылку</a>
    {% endif %}
</div>

<div class="container">
    {% for object in object_list %}
        {% if user == object.owner or perms.app_mailing.view_mailingsrv %}
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                {% if object.is_activated %}
                                <small class="text-body-secondary activated" style="color: green;">активна</small>
                                {% else %}
                                <small class="text-body-secondary" style="color: red;">заблокирована</small>
                                {% endif %}
                            </div>
                        </li>
                    </ol>
                </div>
                    <h4 class="my-0 font-weight-normal">Рассылка номер: {{ object.id }}</h4>
                </div>
                <div class="card-body">
                    <details>
                        <summary>Посмотреть</summary>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Периодичность рассылки: {{ object.frequency }}</li>
                            <li>Время начала рассылки: {{ object.start }}</li>
                            <li>Время завершения рассылки: {{ object.finish }}</li>
                            <li>Статус рассылки: {{ object.status }}</li>
                        </ul>
                    </details>

                    <div class="btn-group">
                        <a href="{% url 'app_mailing:mailings_detail' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Подробности</a>
                        {% if user.is_superuser or not user.groups.exists %}
                        {% if object.is_activated %}
                        <form action="{% url 'app_mailing:send_mailing_btn' object.pk %}" method="post">
                        {%csrf_token%}
                            <button class="btn btn-success" type="submit">Выполнить</button>
                        </form>
                        {% endif %}
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}