app_blog/urls.py
from app_blog.apps import AppBlogConfig
from django.urls import path

from app_blog.views import BlogpostListView, BlogpostCreateView, BlogpostDetailView, BlogpostUpdateView, \
    BlogpostDeleteView

app_name = AppBlogConfig.name

urlpatterns = [
    path('', BlogpostListView.as_view(), name='post_list'),
    path('post_create/', BlogpostCreateView.as_view(), name='post_create'),
    path('post_view/<int:pk>/', BlogpostDetailView.as_view(), name='post_view'),
    path('post_update/<int:pk>/', BlogpostUpdateView.as_view(), name='post_update'),
    path('post_delete/<int:pk>/', BlogpostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_mailing.urls', namespace='app_mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('app_blog.urls', namespace='app_blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, get_verification, RegisterInfo, UserListView, \
    UserUpdateView, UserDetailView, UserDeleteView, PasswordResetView, UserPasswordChangeView, PasswordResetDoneView, \
    PasswordResetCompleteView, MyPasswordResetConfirmView, UserCustomUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification_check/', RegisterInfo.as_view(), name='verification_check'),
    path('email_verify/<str:verification_code>/', get_verification, name='verification'),
    path('verification_approve/', TemplateView.as_view(
        template_name='users/verification_approve.html'), name='verification_approve'),
    path('verification_reject/', TemplateView.as_view(
        template_name='users/verification_reject.html'), name='verification_reject'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('user_custom_update/<int:pk>/', UserCustomUpdateView.as_view(), name='user_custom_update'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('user_delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

app_blog/models.py
from django.db import models

# Create your models here.

NULLABLE = {
    'null': True,
    'blank': True,
}


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='app_blog/', verbose_name='изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    def __str__(self):
        return f'Публикация: {self.title}'

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = "публикации"
        ordering = ("-date_create",)

app_blog/forms.py
from django import forms

from app_blog.models import Blogpost


class StyleFormMiXin(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


class BlogpostForm(StyleFormMiXin, forms.ModelForm):
    class Meta:
        model = Blogpost
        # fields = '__all__'
        fields = ('title', 'content', 'preview', 'is_published',)

app_blog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy, reverse

from app_blog.forms import BlogpostForm
from app_blog.models import Blogpost
from app_blog.services import get_cache_blogposts

from app_mailing.views import BaseContextMixin


# Create your views here.


class BlogpostListView(BaseContextMixin, ListView):
    model = Blogpost
    extra_context = {
        'title': 'Публикации'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff and not self.request.user.is_superuser:
            queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = get_cache_blogposts()

        return context_data


class BlogpostCreateView(PermissionRequiredMixin, BaseContextMixin, CreateView):
    model = Blogpost
    form_class = BlogpostForm
    success_url = reverse_lazy('app_blog:post_list')
    permission_required = 'app_blog.add_blogpost'

    extra_context = {
        'title': 'Создание публикации'
    }

    def handle_no_permission(self):
        return redirect('app_mailing:access_denied')


class BlogpostDetailView(BaseContextMixin, DetailView):
    model = Blogpost
    extra_context = {
        'title': 'Публикация'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogpostUpdateView(PermissionRequiredMixin, BaseContextMixin, UpdateView):
    model = Blogpost
    form_class = BlogpostForm
    # success_url = reverse_lazy('app_blog:post_view')
    permission_required = 'app_blog.change_blogpost'

    extra_context = {
        'title': 'Редакция публикации'
    }

    def get_success_url(self):
        return reverse('app_blog:post_view', args=[self.object.pk])

    def handle_no_permission(self):
        return redirect('app_mailing:access_denied')


class BlogpostDeleteView(PermissionRequiredMixin, BaseContextMixin, DeleteView):
    model = Blogpost
    success_url = reverse_lazy('app_blog:post_list')
    permission_required = 'app_blog.delete_blogpost'

    extra_context = {
        'title': 'Удаление публикации'
    }

    def handle_no_permission(self):
        return redirect('app_mailing:access_denied')


def custom_permission_denied(request):
    context = {
        'logged_in_user_email': request.user.email if request.user.is_authenticated else None
    }
    return render(request, 'app_mailing/access_denied.html', context=context)

app_blog/templates/app_blog/blogpost_confirm_delete.html
{% extends 'app_mailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Вы действительно хотите удалить запись "{{ object.title }}" ?</p>
                                   <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'app_blog:post_view' object.pk %}" class="btn btn-sm btn-outline-primary">Назад</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_blog/templates/app_blog/blogpost_detail.html
{% extends 'app_mailing/base.html' %}

{% load blog_tags %}

{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <small class="text-body-secondary">Просмотры:</small>
                            </div>
                            <span class="badge bg-primary rounded-pill">{{ object.views_count }}</span>
                        </li>
                    </ol>
                </div>
                <h4 class="card-title">{{ object.title }}</h4>
            </div>
            <div class="card-body">
                <img src="{% media_tag object.preview %}" class="img-fluid rounded-start" alt="Image">
                <hr>
                <p class="card-text">{{ object.content }}</p>
            </div>

            <div class="card-footer">
                <div class="d-flex w-100 justify-content-between">
                    <small class="text-body-secondary">Дата публикации: {{ object.date_create }}</small>
                </div>
                <div class="btn-group">
                <a href="{% url 'app_blog:post_list' %}" class="btn btn-sm btn-outline-primary">К списку</a>
                {% if user.is_superuser or user.groups.exists %}
                    <a href="{% url 'app_blog:post_update' object.pk %}" class="btn btn-sm btn-outline-primary">Редактировать</a>
                    <a href="{% url 'app_blog:post_delete' object.pk %}"
                       class="btn btn-sm btn-outline-primary">Удалить</a>
                {% endif %}
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_blog/templates/app_blog/blogpost_form.html
{% extends 'app_mailing/base.html' %}

{% block content %}

<div class="card mb-3" style="max-width: 100%;">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-sm btn-outline-success">
                            {% if object %}
                                Сохранить изменения
                            {% else %}
                                Создать публикацию
                            {% endif %}
                        </button>
                        <div class="btn-group">
                            <a href="{% url 'app_blog:post_list' %}" class="btn btn-sm btn-outline-primary">К списку</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_blog/templates/app_blog/blogpost_list.html
{% extends 'app_mailing/base.html' %}


{% block content %}

<div class="container">
    <a href="{% url 'app_blog:post_create' %}" class="btn btn-primary">Добавить запись</a>
</div>

<div class="container">

    {% for object in object_list %}

    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <div class="d-flex justify-content-end mt-auto">
                    <ol class="list-group list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <small class="text-body-secondary">Просмотры:</small>
                            </div>
                            <span class="badge bg-primary rounded-pill">{{ object.views_count }}</span>
                        </li>
                    </ol>
                </div>
                <h4 class="card-title">{{ object.title }}</h4>
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.content | truncatechars:111 }}</p>
            </div>

            <div class="card-footer">
                <div class="d-flex w-100 justify-content-between">
                    <small class="text-body-secondary">Дата публикации: {{ object.date_create }}</small>
                </div>
                <div class="btn-group">
                <a href="{% url 'app_blog:post_view' object.pk %}" class="btn btn-sm btn-outline-primary">Просмотр записи</a>
            </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}